# Generated by Django 5.2.17 on 2026-09-28 08:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0002_row_level_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopmembership',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='accounts.role')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.shop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True)), fields=('shop', 'email'), name='one_pending_invitation_per_email')],
            },
        ),
    ]
