# Generated by Django 5.2.17 on 2026-09-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_device_approved_at_shopmembership_is_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='credential_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='credential_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
