# Generated by Django 5.2.17 on 2026-09-28 10:24

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0002_row_level_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.shop')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('order_number', models.CharField(max_length=80)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='tenants.branch')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.shop')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.purchaseorder')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('product__isnull', False), ('variant__isnull', False), _connector='OR'), name='purchase_item_has_target')],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19)),
                ('low_stock_threshold', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='tenants.branch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='catalog.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.shop')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('shop', 'branch', 'product'), name='unique_product_balance_per_branch'), models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('shop', 'branch', 'variant'), name='unique_variant_balance_per_branch'), models.CheckConstraint(condition=models.Q(('product__isnull', False), ('variant__isnull', False), _connector='OR'), name='balance_has_target')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('movement_type', models.CharField(choices=[('opening', 'Opening balance'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out')], max_length=24)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=19)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reference_type', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='tenants.branch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.shop')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='movement_quantity_nonzero'), models.CheckConstraint(condition=models.Q(('product__isnull', False), ('variant__isnull', False), _connector='OR'), name='movement_has_target')],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('shop', 'name'), name='unique_supplier_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('shop', 'order_number'), name='unique_purchase_number_per_shop'),
        ),
    ]
